// Code generated by protoc-gen-go.
// source: d21.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	d21.proto

It has these top-level messages:
	TxBeginRequest
	TxBeginResponse
	TxCommitRequest
	TxCommitResponse
	TxRollbackRequest
	TxRollbackResponse
	Request
	TxRequest
	TxResponse
	ControlTypeString
	Entry
	EntryAttribute
	Response
	Metadata
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// LDAP Search scope
type SearchScope int32

const (
	SearchScope_BaseObject  SearchScope = 0
	SearchScope_SingleLevel SearchScope = 1
	SearchScope_Subtree     SearchScope = 2
)

var SearchScope_name = map[int32]string{
	0: "BaseObject",
	1: "SingleLevel",
	2: "Subtree",
}
var SearchScope_value = map[string]int32{
	"BaseObject":  0,
	"SingleLevel": 1,
	"Subtree":     2,
}

func (x SearchScope) String() string {
	return proto.EnumName(SearchScope_name, int32(x))
}
func (SearchScope) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RESTMethod int32

const (
	RESTMethod_UNKNOWN RESTMethod = 0
	RESTMethod_GET     RESTMethod = 1
	RESTMethod_PUT     RESTMethod = 2
	RESTMethod_POST    RESTMethod = 3
	RESTMethod_DELETE  RESTMethod = 4
	RESTMethod_SYNC    RESTMethod = 5
	RESTMethod_QGET    RESTMethod = 6
)

var RESTMethod_name = map[int32]string{
	0: "UNKNOWN",
	1: "GET",
	2: "PUT",
	3: "POST",
	4: "DELETE",
	5: "SYNC",
	6: "QGET",
}
var RESTMethod_value = map[string]int32{
	"UNKNOWN": 0,
	"GET":     1,
	"PUT":     2,
	"POST":    3,
	"DELETE":  4,
	"SYNC":    5,
	"QGET":    6,
}

func (x RESTMethod) String() string {
	return proto.EnumName(RESTMethod_name, int32(x))
}
func (RESTMethod) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type EntryMethod int32

const (
	EntryMethod_Unknown  EntryMethod = 0
	EntryMethod_Add      EntryMethod = 1
	EntryMethod_Replace  EntryMethod = 2
	EntryMethod_Delete   EntryMethod = 3
	EntryMethod_Increase EntryMethod = 4
)

var EntryMethod_name = map[int32]string{
	0: "Unknown",
	1: "Add",
	2: "Replace",
	3: "Delete",
	4: "Increase",
}
var EntryMethod_value = map[string]int32{
	"Unknown":  0,
	"Add":      1,
	"Replace":  2,
	"Delete":   3,
	"Increase": 4,
}

func (x EntryMethod) String() string {
	return proto.EnumName(EntryMethod_name, int32(x))
}
func (EntryMethod) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type TxMethod int32

const (
	TxMethod_TXUNKNOWN  TxMethod = 0
	TxMethod_TXBEGIN    TxMethod = 1
	TxMethod_TXDO       TxMethod = 2
	TxMethod_TXCOMMIT   TxMethod = 3
	TxMethod_TXROLLBACK TxMethod = 4
	TxMethod_TXUNDO     TxMethod = 5
	TxMethod_TXLOCK     TxMethod = 6
	TxMethod_TXSTORE    TxMethod = 7
)

var TxMethod_name = map[int32]string{
	0: "TXUNKNOWN",
	1: "TXBEGIN",
	2: "TXDO",
	3: "TXCOMMIT",
	4: "TXROLLBACK",
	5: "TXUNDO",
	6: "TXLOCK",
	7: "TXSTORE",
}
var TxMethod_value = map[string]int32{
	"TXUNKNOWN":  0,
	"TXBEGIN":    1,
	"TXDO":       2,
	"TXCOMMIT":   3,
	"TXROLLBACK": 4,
	"TXUNDO":     5,
	"TXLOCK":     6,
	"TXSTORE":    7,
}

func (x TxMethod) String() string {
	return proto.EnumName(TxMethod_name, int32(x))
}
func (TxMethod) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type TxBeginRequest struct {
}

func (m *TxBeginRequest) Reset()                    { *m = TxBeginRequest{} }
func (m *TxBeginRequest) String() string            { return proto.CompactTextString(m) }
func (*TxBeginRequest) ProtoMessage()               {}
func (*TxBeginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TxBeginResponse struct {
	TID      uint64    `protobuf:"varint,1,opt,name=TID" json:"TID,omitempty"`
	Metadata *Metadata `protobuf:"bytes,2,opt,name=Metadata" json:"Metadata,omitempty"`
}

func (m *TxBeginResponse) Reset()                    { *m = TxBeginResponse{} }
func (m *TxBeginResponse) String() string            { return proto.CompactTextString(m) }
func (*TxBeginResponse) ProtoMessage()               {}
func (*TxBeginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TxBeginResponse) GetTID() uint64 {
	if m != nil {
		return m.TID
	}
	return 0
}

func (m *TxBeginResponse) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type TxCommitRequest struct {
	TID uint64 `protobuf:"varint,1,opt,name=TID" json:"TID,omitempty"`
}

func (m *TxCommitRequest) Reset()                    { *m = TxCommitRequest{} }
func (m *TxCommitRequest) String() string            { return proto.CompactTextString(m) }
func (*TxCommitRequest) ProtoMessage()               {}
func (*TxCommitRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TxCommitRequest) GetTID() uint64 {
	if m != nil {
		return m.TID
	}
	return 0
}

type TxCommitResponse struct {
	TID      uint64    `protobuf:"varint,1,opt,name=TID" json:"TID,omitempty"`
	Metadata *Metadata `protobuf:"bytes,2,opt,name=Metadata" json:"Metadata,omitempty"`
}

func (m *TxCommitResponse) Reset()                    { *m = TxCommitResponse{} }
func (m *TxCommitResponse) String() string            { return proto.CompactTextString(m) }
func (*TxCommitResponse) ProtoMessage()               {}
func (*TxCommitResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TxCommitResponse) GetTID() uint64 {
	if m != nil {
		return m.TID
	}
	return 0
}

func (m *TxCommitResponse) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type TxRollbackRequest struct {
	TID uint64 `protobuf:"varint,1,opt,name=TID" json:"TID,omitempty"`
}

func (m *TxRollbackRequest) Reset()                    { *m = TxRollbackRequest{} }
func (m *TxRollbackRequest) String() string            { return proto.CompactTextString(m) }
func (*TxRollbackRequest) ProtoMessage()               {}
func (*TxRollbackRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TxRollbackRequest) GetTID() uint64 {
	if m != nil {
		return m.TID
	}
	return 0
}

type TxRollbackResponse struct {
	TID      uint64    `protobuf:"varint,1,opt,name=TID" json:"TID,omitempty"`
	Metadata *Metadata `protobuf:"bytes,2,opt,name=Metadata" json:"Metadata,omitempty"`
}

func (m *TxRollbackResponse) Reset()                    { *m = TxRollbackResponse{} }
func (m *TxRollbackResponse) String() string            { return proto.CompactTextString(m) }
func (*TxRollbackResponse) ProtoMessage()               {}
func (*TxRollbackResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *TxRollbackResponse) GetTID() uint64 {
	if m != nil {
		return m.TID
	}
	return 0
}

func (m *TxRollbackResponse) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// Request
type Request struct {
	// option (gogoproto.face)            = false;
	ID                 uint64             `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Time               int64              `protobuf:"varint,2,opt,name=Time" json:"Time,omitempty"`
	Method             RESTMethod         `protobuf:"varint,3,opt,name=Method,enum=pb.RESTMethod" json:"Method,omitempty"`
	BaseDn             string             `protobuf:"bytes,4,opt,name=BaseDn" json:"BaseDn,omitempty"`
	Filter             string             `protobuf:"bytes,5,opt,name=Filter" json:"Filter,omitempty"`
	Attributes         []string           `protobuf:"bytes,6,rep,name=Attributes" json:"Attributes,omitempty"`
	Scope              SearchScope        `protobuf:"varint,7,opt,name=Scope,enum=pb.SearchScope" json:"Scope,omitempty"`
	Entry              *Entry             `protobuf:"bytes,8,opt,name=Entry" json:"Entry,omitempty"`
	Dn                 string             `protobuf:"bytes,9,opt,name=Dn" json:"Dn,omitempty"`
	Recursive          bool               `protobuf:"varint,10,opt,name=Recursive" json:"Recursive,omitempty"`
	DerefAliases       int32              `protobuf:"varint,11,opt,name=DerefAliases" json:"DerefAliases,omitempty"`
	SizeLimit          int32              `protobuf:"varint,12,opt,name=SizeLimit" json:"SizeLimit,omitempty"`
	TimeLimit          int32              `protobuf:"varint,13,opt,name=TimeLimit" json:"TimeLimit,omitempty"`
	TypesOnly          bool               `protobuf:"varint,14,opt,name=TypesOnly" json:"TypesOnly,omitempty"`
	ControlString      *ControlTypeString `protobuf:"bytes,15,opt,name=ControlString" json:"ControlString,omitempty"`
	GID                uint64             `protobuf:"varint,16,opt,name=GID" json:"GID,omitempty"`
	TID                uint64             `protobuf:"varint,17,opt,name=TID" json:"TID,omitempty"`
	TxMethod           TxMethod           `protobuf:"varint,18,opt,name=TxMethod,enum=pb.TxMethod" json:"TxMethod,omitempty"`
	UUID               uint64             `protobuf:"varint,19,opt,name=UUID" json:"UUID,omitempty"`
	ApplicationName    string             `protobuf:"bytes,51,opt,name=ApplicationName" json:"ApplicationName,omitempty"`
	ApplicationMethod  string             `protobuf:"bytes,52,opt,name=ApplicationMethod" json:"ApplicationMethod,omitempty"`
	ApplicationVersion uint32             `protobuf:"varint,53,opt,name=ApplicationVersion" json:"ApplicationVersion,omitempty"`
	ApplicationPayload string             `protobuf:"bytes,54,opt,name=ApplicationPayload" json:"ApplicationPayload,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Request) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Request) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Request) GetMethod() RESTMethod {
	if m != nil {
		return m.Method
	}
	return RESTMethod_UNKNOWN
}

func (m *Request) GetBaseDn() string {
	if m != nil {
		return m.BaseDn
	}
	return ""
}

func (m *Request) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *Request) GetAttributes() []string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Request) GetScope() SearchScope {
	if m != nil {
		return m.Scope
	}
	return SearchScope_BaseObject
}

func (m *Request) GetEntry() *Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func (m *Request) GetDn() string {
	if m != nil {
		return m.Dn
	}
	return ""
}

func (m *Request) GetRecursive() bool {
	if m != nil {
		return m.Recursive
	}
	return false
}

func (m *Request) GetDerefAliases() int32 {
	if m != nil {
		return m.DerefAliases
	}
	return 0
}

func (m *Request) GetSizeLimit() int32 {
	if m != nil {
		return m.SizeLimit
	}
	return 0
}

func (m *Request) GetTimeLimit() int32 {
	if m != nil {
		return m.TimeLimit
	}
	return 0
}

func (m *Request) GetTypesOnly() bool {
	if m != nil {
		return m.TypesOnly
	}
	return false
}

func (m *Request) GetControlString() *ControlTypeString {
	if m != nil {
		return m.ControlString
	}
	return nil
}

func (m *Request) GetGID() uint64 {
	if m != nil {
		return m.GID
	}
	return 0
}

func (m *Request) GetTID() uint64 {
	if m != nil {
		return m.TID
	}
	return 0
}

func (m *Request) GetTxMethod() TxMethod {
	if m != nil {
		return m.TxMethod
	}
	return TxMethod_TXUNKNOWN
}

func (m *Request) GetUUID() uint64 {
	if m != nil {
		return m.UUID
	}
	return 0
}

func (m *Request) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *Request) GetApplicationMethod() string {
	if m != nil {
		return m.ApplicationMethod
	}
	return ""
}

func (m *Request) GetApplicationVersion() uint32 {
	if m != nil {
		return m.ApplicationVersion
	}
	return 0
}

func (m *Request) GetApplicationPayload() string {
	if m != nil {
		return m.ApplicationPayload
	}
	return ""
}

type TxRequest struct {
	ID       uint64     `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Time     int64      `protobuf:"varint,2,opt,name=Time" json:"Time,omitempty"`
	Requests []*Request `protobuf:"bytes,3,rep,name=Requests" json:"Requests,omitempty"`
}

func (m *TxRequest) Reset()                    { *m = TxRequest{} }
func (m *TxRequest) String() string            { return proto.CompactTextString(m) }
func (*TxRequest) ProtoMessage()               {}
func (*TxRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *TxRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *TxRequest) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *TxRequest) GetRequests() []*Request {
	if m != nil {
		return m.Requests
	}
	return nil
}

type TxResponse struct {
	ID               uint64    `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	LastSuccessIndex int32     `protobuf:"varint,2,opt,name=LastSuccessIndex" json:"LastSuccessIndex,omitempty"`
	Response         *Response `protobuf:"bytes,3,opt,name=Response" json:"Response,omitempty"`
}

func (m *TxResponse) Reset()                    { *m = TxResponse{} }
func (m *TxResponse) String() string            { return proto.CompactTextString(m) }
func (*TxResponse) ProtoMessage()               {}
func (*TxResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *TxResponse) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *TxResponse) GetLastSuccessIndex() int32 {
	if m != nil {
		return m.LastSuccessIndex
	}
	return 0
}

func (m *TxResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

type ControlTypeString struct {
	ControlType  string `protobuf:"bytes,1,opt,name=ControlType" json:"ControlType,omitempty"`
	Criticality  bool   `protobuf:"varint,2,opt,name=Criticality" json:"Criticality,omitempty"`
	ControlValue string `protobuf:"bytes,3,opt,name=ControlValue" json:"ControlValue,omitempty"`
}

func (m *ControlTypeString) Reset()                    { *m = ControlTypeString{} }
func (m *ControlTypeString) String() string            { return proto.CompactTextString(m) }
func (*ControlTypeString) ProtoMessage()               {}
func (*ControlTypeString) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ControlTypeString) GetControlType() string {
	if m != nil {
		return m.ControlType
	}
	return ""
}

func (m *ControlTypeString) GetCriticality() bool {
	if m != nil {
		return m.Criticality
	}
	return false
}

func (m *ControlTypeString) GetControlValue() string {
	if m != nil {
		return m.ControlValue
	}
	return ""
}

// Entry represents on single Dn in LDAP
type Entry struct {
	// option (gogoproto.face)            = false;
	Dn         string            `protobuf:"bytes,1,opt,name=Dn" json:"Dn,omitempty"`
	ModDn      bool              `protobuf:"varint,2,opt,name=ModDn" json:"ModDn,omitempty"`
	Attributes []*EntryAttribute `protobuf:"bytes,3,rep,name=Attributes" json:"Attributes,omitempty"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Entry) GetDn() string {
	if m != nil {
		return m.Dn
	}
	return ""
}

func (m *Entry) GetModDn() bool {
	if m != nil {
		return m.ModDn
	}
	return false
}

func (m *Entry) GetAttributes() []*EntryAttribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

// Key value pair
type EntryAttribute struct {
	// option (gogoproto.face)            = false;
	Method EntryMethod `protobuf:"varint,1,opt,name=Method,enum=pb.EntryMethod" json:"Method,omitempty"`
	Name   string      `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Values []string    `protobuf:"bytes,3,rep,name=Values" json:"Values,omitempty"`
}

func (m *EntryAttribute) Reset()                    { *m = EntryAttribute{} }
func (m *EntryAttribute) String() string            { return proto.CompactTextString(m) }
func (*EntryAttribute) ProtoMessage()               {}
func (*EntryAttribute) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *EntryAttribute) GetMethod() EntryMethod {
	if m != nil {
		return m.Method
	}
	return EntryMethod_Unknown
}

func (m *EntryAttribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EntryAttribute) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

// Response
type Response struct {
	// option (gogoproto.face)            = false;
	ID                uint64    `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	GID               uint64    `protobuf:"varint,2,opt,name=GID" json:"GID,omitempty"`
	Metadata          *Metadata `protobuf:"bytes,3,opt,name=Metadata" json:"Metadata,omitempty"`
	ResultCode        uint32    `protobuf:"varint,4,opt,name=ResultCode" json:"ResultCode,omitempty"`
	MatchedDn         string    `protobuf:"bytes,5,opt,name=MatchedDn" json:"MatchedDn,omitempty"`
	ResultDescription string    `protobuf:"bytes,6,opt,name=ResultDescription" json:"ResultDescription,omitempty"`
	Entries           []*Entry  `protobuf:"bytes,7,rep,name=Entries" json:"Entries,omitempty"`
	Referrals         []string  `protobuf:"bytes,8,rep,name=Referrals" json:"Referrals,omitempty"`
	Controls          []string  `protobuf:"bytes,9,rep,name=Controls" json:"Controls,omitempty"`
	TID               uint64    `protobuf:"varint,10,opt,name=TID" json:"TID,omitempty"`
	StreamFlag        uint32    `protobuf:"varint,11,opt,name=StreamFlag" json:"StreamFlag,omitempty"`
	StatusCode        uint32    `protobuf:"varint,12,opt,name=StatusCode" json:"StatusCode,omitempty"`
	Status            string    `protobuf:"bytes,13,opt,name=Status" json:"Status,omitempty"`
	StatusCodeMessage string    `protobuf:"bytes,14,opt,name=StatusCodeMessage" json:"StatusCodeMessage,omitempty"`
	Message           string    `protobuf:"bytes,15,opt,name=Message" json:"Message,omitempty"`
	Data              string    `protobuf:"bytes,16,opt,name=Data" json:"Data,omitempty"`
	Count             uint64    `protobuf:"varint,17,opt,name=Count" json:"Count,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Response) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Response) GetGID() uint64 {
	if m != nil {
		return m.GID
	}
	return 0
}

func (m *Response) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Response) GetResultCode() uint32 {
	if m != nil {
		return m.ResultCode
	}
	return 0
}

func (m *Response) GetMatchedDn() string {
	if m != nil {
		return m.MatchedDn
	}
	return ""
}

func (m *Response) GetResultDescription() string {
	if m != nil {
		return m.ResultDescription
	}
	return ""
}

func (m *Response) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *Response) GetReferrals() []string {
	if m != nil {
		return m.Referrals
	}
	return nil
}

func (m *Response) GetControls() []string {
	if m != nil {
		return m.Controls
	}
	return nil
}

func (m *Response) GetTID() uint64 {
	if m != nil {
		return m.TID
	}
	return 0
}

func (m *Response) GetStreamFlag() uint32 {
	if m != nil {
		return m.StreamFlag
	}
	return 0
}

func (m *Response) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *Response) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Response) GetStatusCodeMessage() string {
	if m != nil {
		return m.StatusCodeMessage
	}
	return ""
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Response) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

// Meta data is used to return meta data to response
type Metadata struct {
	NodeID    uint64 `protobuf:"varint,1,opt,name=NodeID" json:"NodeID,omitempty"`
	ClusterID uint64 `protobuf:"varint,2,opt,name=ClusterID" json:"ClusterID,omitempty"`
	RaftIndex uint64 `protobuf:"varint,3,opt,name=RaftIndex" json:"RaftIndex,omitempty"`
	RaftTerm  uint64 `protobuf:"varint,4,opt,name=RaftTerm" json:"RaftTerm,omitempty"`
}

func (m *Metadata) Reset()                    { *m = Metadata{} }
func (m *Metadata) String() string            { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()               {}
func (*Metadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *Metadata) GetNodeID() uint64 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

func (m *Metadata) GetClusterID() uint64 {
	if m != nil {
		return m.ClusterID
	}
	return 0
}

func (m *Metadata) GetRaftIndex() uint64 {
	if m != nil {
		return m.RaftIndex
	}
	return 0
}

func (m *Metadata) GetRaftTerm() uint64 {
	if m != nil {
		return m.RaftTerm
	}
	return 0
}

func init() {
	proto.RegisterType((*TxBeginRequest)(nil), "pb.TxBeginRequest")
	proto.RegisterType((*TxBeginResponse)(nil), "pb.TxBeginResponse")
	proto.RegisterType((*TxCommitRequest)(nil), "pb.TxCommitRequest")
	proto.RegisterType((*TxCommitResponse)(nil), "pb.TxCommitResponse")
	proto.RegisterType((*TxRollbackRequest)(nil), "pb.TxRollbackRequest")
	proto.RegisterType((*TxRollbackResponse)(nil), "pb.TxRollbackResponse")
	proto.RegisterType((*Request)(nil), "pb.Request")
	proto.RegisterType((*TxRequest)(nil), "pb.TxRequest")
	proto.RegisterType((*TxResponse)(nil), "pb.TxResponse")
	proto.RegisterType((*ControlTypeString)(nil), "pb.ControlTypeString")
	proto.RegisterType((*Entry)(nil), "pb.Entry")
	proto.RegisterType((*EntryAttribute)(nil), "pb.EntryAttribute")
	proto.RegisterType((*Response)(nil), "pb.Response")
	proto.RegisterType((*Metadata)(nil), "pb.Metadata")
	proto.RegisterEnum("pb.SearchScope", SearchScope_name, SearchScope_value)
	proto.RegisterEnum("pb.RESTMethod", RESTMethod_name, RESTMethod_value)
	proto.RegisterEnum("pb.EntryMethod", EntryMethod_name, EntryMethod_value)
	proto.RegisterEnum("pb.TxMethod", TxMethod_name, TxMethod_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for D21 service

type D21Client interface {
	Do(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	ResolveAlias(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	AtomicAdd(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	TxBegin(ctx context.Context, in *TxBeginRequest, opts ...grpc.CallOption) (*TxBeginResponse, error)
	TxDo(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	TxCommit(ctx context.Context, in *TxCommitRequest, opts ...grpc.CallOption) (*TxCommitResponse, error)
	TxRollback(ctx context.Context, in *TxRollbackRequest, opts ...grpc.CallOption) (*TxRollbackResponse, error)
	GetStream(ctx context.Context, in *Request, opts ...grpc.CallOption) (D21_GetStreamClient, error)
}

type d21Client struct {
	cc *grpc.ClientConn
}

func NewD21Client(cc *grpc.ClientConn) D21Client {
	return &d21Client{cc}
}

func (c *d21Client) Do(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/pb.D21/Do", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *d21Client) ResolveAlias(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/pb.D21/ResolveAlias", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *d21Client) AtomicAdd(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/pb.D21/AtomicAdd", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *d21Client) TxBegin(ctx context.Context, in *TxBeginRequest, opts ...grpc.CallOption) (*TxBeginResponse, error) {
	out := new(TxBeginResponse)
	err := grpc.Invoke(ctx, "/pb.D21/TxBegin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *d21Client) TxDo(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/pb.D21/TxDo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *d21Client) TxCommit(ctx context.Context, in *TxCommitRequest, opts ...grpc.CallOption) (*TxCommitResponse, error) {
	out := new(TxCommitResponse)
	err := grpc.Invoke(ctx, "/pb.D21/TxCommit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *d21Client) TxRollback(ctx context.Context, in *TxRollbackRequest, opts ...grpc.CallOption) (*TxRollbackResponse, error) {
	out := new(TxRollbackResponse)
	err := grpc.Invoke(ctx, "/pb.D21/TxRollback", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *d21Client) GetStream(ctx context.Context, in *Request, opts ...grpc.CallOption) (D21_GetStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_D21_serviceDesc.Streams[0], c.cc, "/pb.D21/GetStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &d21GetStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type D21_GetStreamClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type d21GetStreamClient struct {
	grpc.ClientStream
}

func (x *d21GetStreamClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for D21 service

type D21Server interface {
	Do(context.Context, *Request) (*Response, error)
	ResolveAlias(context.Context, *Request) (*Response, error)
	AtomicAdd(context.Context, *Request) (*Response, error)
	TxBegin(context.Context, *TxBeginRequest) (*TxBeginResponse, error)
	TxDo(context.Context, *Request) (*Response, error)
	TxCommit(context.Context, *TxCommitRequest) (*TxCommitResponse, error)
	TxRollback(context.Context, *TxRollbackRequest) (*TxRollbackResponse, error)
	GetStream(*Request, D21_GetStreamServer) error
}

func RegisterD21Server(s *grpc.Server, srv D21Server) {
	s.RegisterService(&_D21_serviceDesc, srv)
}

func _D21_Do_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(D21Server).Do(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.D21/Do",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(D21Server).Do(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _D21_ResolveAlias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(D21Server).ResolveAlias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.D21/ResolveAlias",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(D21Server).ResolveAlias(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _D21_AtomicAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(D21Server).AtomicAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.D21/AtomicAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(D21Server).AtomicAdd(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _D21_TxBegin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxBeginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(D21Server).TxBegin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.D21/TxBegin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(D21Server).TxBegin(ctx, req.(*TxBeginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _D21_TxDo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(D21Server).TxDo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.D21/TxDo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(D21Server).TxDo(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _D21_TxCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(D21Server).TxCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.D21/TxCommit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(D21Server).TxCommit(ctx, req.(*TxCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _D21_TxRollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxRollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(D21Server).TxRollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.D21/TxRollback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(D21Server).TxRollback(ctx, req.(*TxRollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _D21_GetStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(D21Server).GetStream(m, &d21GetStreamServer{stream})
}

type D21_GetStreamServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type d21GetStreamServer struct {
	grpc.ServerStream
}

func (x *d21GetStreamServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

var _D21_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.D21",
	HandlerType: (*D21Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Do",
			Handler:    _D21_Do_Handler,
		},
		{
			MethodName: "ResolveAlias",
			Handler:    _D21_ResolveAlias_Handler,
		},
		{
			MethodName: "AtomicAdd",
			Handler:    _D21_AtomicAdd_Handler,
		},
		{
			MethodName: "TxBegin",
			Handler:    _D21_TxBegin_Handler,
		},
		{
			MethodName: "TxDo",
			Handler:    _D21_TxDo_Handler,
		},
		{
			MethodName: "TxCommit",
			Handler:    _D21_TxCommit_Handler,
		},
		{
			MethodName: "TxRollback",
			Handler:    _D21_TxRollback_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetStream",
			Handler:       _D21_GetStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "d21.proto",
}

func init() { proto.RegisterFile("d21.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x56, 0x6d, 0x6f, 0xdb, 0xb6,
	0x13, 0xaf, 0x24, 0x3f, 0xe9, 0x9c, 0x38, 0x0a, 0xfb, 0x00, 0x21, 0xf8, 0xa3, 0xf5, 0xdf, 0x45,
	0x5b, 0x2f, 0x18, 0x82, 0xd5, 0x5d, 0xf7, 0xa6, 0xaf, 0x1c, 0xcb, 0x0d, 0xbc, 0xfa, 0x21, 0xa3,
	0x95, 0x2e, 0x7b, 0x29, 0xcb, 0xd7, 0x54, 0xab, 0x2c, 0x79, 0x22, 0x9d, 0x25, 0xdd, 0x77, 0x1e,
	0xf6, 0x05, 0x06, 0x0c, 0x24, 0x65, 0x49, 0xb6, 0xbb, 0x00, 0x03, 0xfa, 0x8e, 0xf7, 0xfb, 0x1d,
	0xef, 0x8e, 0xc7, 0xbb, 0x23, 0xc1, 0x9c, 0x77, 0x5e, 0x9e, 0x2c, 0x93, 0x98, 0xc7, 0x44, 0x5f,
	0xce, 0x5a, 0x16, 0x34, 0xdc, 0x9b, 0x53, 0xbc, 0x0a, 0x22, 0x8a, 0xbf, 0xad, 0x90, 0xf1, 0xd6,
	0x08, 0x0e, 0x32, 0x84, 0x2d, 0xe3, 0x88, 0x21, 0xb1, 0xc0, 0x70, 0x07, 0x8e, 0xad, 0x35, 0xb5,
	0x76, 0x89, 0x8a, 0x25, 0x69, 0x43, 0x6d, 0x84, 0xdc, 0x9b, 0x7b, 0xdc, 0xb3, 0xf5, 0xa6, 0xd6,
	0xae, 0x77, 0xf6, 0x4e, 0x96, 0xb3, 0x93, 0x35, 0x46, 0x33, 0xb6, 0xf5, 0x54, 0x98, 0xeb, 0xc5,
	0x8b, 0x45, 0xc0, 0x53, 0x0f, 0xbb, 0xe6, 0x5a, 0x63, 0xb0, 0x72, 0xa5, 0xaf, 0xe0, 0xf4, 0x19,
	0x1c, 0xba, 0x37, 0x34, 0x0e, 0xc3, 0x99, 0xe7, 0x7f, 0xfa, 0x77, 0xb7, 0xe7, 0x40, 0x8a, 0x6a,
	0x5f, 0xc1, 0xf1, 0x5f, 0x65, 0xa8, 0xae, 0xfd, 0x35, 0x40, 0xcf, 0xcc, 0xe8, 0x03, 0x87, 0x10,
	0x28, 0xb9, 0xc1, 0x02, 0xa5, 0x05, 0x83, 0xca, 0x35, 0x79, 0x0e, 0x95, 0x11, 0xf2, 0x8f, 0xf1,
	0xdc, 0x36, 0x9a, 0x5a, 0xbb, 0xd1, 0x69, 0x08, 0xbb, 0xb4, 0x3f, 0x75, 0x15, 0x4a, 0x53, 0x96,
	0x3c, 0x82, 0xca, 0xa9, 0xc7, 0xd0, 0x89, 0xec, 0x52, 0x53, 0x6b, 0x9b, 0x34, 0x95, 0x04, 0xfe,
	0x36, 0x08, 0x39, 0x26, 0x76, 0x59, 0xe1, 0x4a, 0x22, 0x8f, 0x01, 0xba, 0x9c, 0x27, 0xc1, 0x6c,
	0xc5, 0x91, 0xd9, 0x95, 0xa6, 0xd1, 0x36, 0x69, 0x01, 0x21, 0xcf, 0xa0, 0x3c, 0xf5, 0xe3, 0x25,
	0xda, 0x55, 0xe9, 0xf6, 0x40, 0xb8, 0x9d, 0xa2, 0x97, 0xf8, 0x1f, 0x25, 0x4c, 0x15, 0x4b, 0x9e,
	0x40, 0xb9, 0x1f, 0xf1, 0xe4, 0xd6, 0xae, 0xc9, 0x53, 0x9b, 0x42, 0x4d, 0x02, 0x54, 0xe1, 0xe2,
	0x8c, 0x4e, 0x64, 0x9b, 0xd2, 0xb7, 0xee, 0x44, 0xe4, 0x7f, 0x60, 0x52, 0xf4, 0x57, 0x09, 0x0b,
	0xae, 0xd1, 0x86, 0xa6, 0xd6, 0xae, 0xd1, 0x1c, 0x20, 0x2d, 0xd8, 0x73, 0x30, 0xc1, 0x0f, 0xdd,
	0x30, 0xf0, 0x18, 0x32, 0xbb, 0xde, 0xd4, 0xda, 0x65, 0xba, 0x81, 0x09, 0x0b, 0xd3, 0xe0, 0x33,
	0x0e, 0x83, 0x45, 0xc0, 0xed, 0x3d, 0xa9, 0x90, 0x03, 0x82, 0x15, 0x79, 0x53, 0xec, 0xbe, 0x62,
	0x33, 0x40, 0xb2, 0xb7, 0x4b, 0x64, 0x93, 0x28, 0xbc, 0xb5, 0x1b, 0xca, 0x7b, 0x06, 0x90, 0x37,
	0xb0, 0xdf, 0x8b, 0x23, 0x9e, 0xc4, 0xe1, 0x94, 0x27, 0x41, 0x74, 0x65, 0x1f, 0xc8, 0x43, 0x3d,
	0x14, 0x87, 0x4a, 0x09, 0xa1, 0xac, 0x48, 0xba, 0xa9, 0x2b, 0x8a, 0xe2, 0x6c, 0xe0, 0xd8, 0x96,
	0x2a, 0x8a, 0xb3, 0x81, 0xb3, 0x2e, 0x93, 0xc3, 0x8d, 0x32, 0x71, 0x6f, 0xd2, 0xeb, 0x24, 0x32,
	0xaf, 0xb2, 0x4c, 0xd6, 0x18, 0xcd, 0x58, 0x51, 0x0a, 0x17, 0x17, 0x03, 0xc7, 0xbe, 0x2f, 0x37,
	0xcb, 0x35, 0x69, 0xc3, 0x41, 0x77, 0xb9, 0x0c, 0x03, 0xdf, 0xe3, 0x41, 0x1c, 0x8d, 0xbd, 0x05,
	0xda, 0xaf, 0x64, 0x5e, 0xb7, 0x61, 0xf2, 0x2d, 0x1c, 0x16, 0xa0, 0xd4, 0xe1, 0xf7, 0x52, 0x77,
	0x97, 0x20, 0x27, 0x40, 0x0a, 0xe0, 0x7b, 0x4c, 0x58, 0x10, 0x47, 0xf6, 0xeb, 0xa6, 0xd6, 0xde,
	0xa7, 0x5f, 0x60, 0xb6, 0xf4, 0xcf, 0xbd, 0xdb, 0x30, 0xf6, 0xe6, 0xf6, 0x0f, 0xd2, 0xfc, 0x17,
	0x98, 0xd6, 0x25, 0x98, 0xee, 0xcd, 0x7f, 0xa9, 0xf9, 0x17, 0x50, 0x4b, 0xd5, 0x99, 0x6d, 0x34,
	0x8d, 0x76, 0xbd, 0x53, 0x97, 0x55, 0xaf, 0x30, 0x9a, 0x91, 0xad, 0x04, 0x40, 0x58, 0x4e, 0xdb,
	0x72, 0xdb, 0xf4, 0x31, 0x58, 0x43, 0x8f, 0xf1, 0xe9, 0xca, 0xf7, 0x91, 0xb1, 0x41, 0x34, 0xc7,
	0x1b, 0xe9, 0xa6, 0x4c, 0x77, 0x70, 0x71, 0x33, 0x6b, 0x3b, 0xb2, 0xd1, 0xd2, 0x06, 0x5e, 0x63,
	0x34, 0x63, 0x5b, 0x7f, 0xc0, 0xe1, 0x4e, 0x2d, 0x90, 0x26, 0xd4, 0x0b, 0xa0, 0x8c, 0xc1, 0xa4,
	0x45, 0x48, 0x6a, 0x24, 0x01, 0x0f, 0x7c, 0x2f, 0x0c, 0xf8, 0xad, 0x8c, 0xa3, 0x46, 0x8b, 0x90,
	0xa8, 0xfd, 0x74, 0xc3, 0x7b, 0x2f, 0x5c, 0xa9, 0x30, 0x4c, 0xba, 0x81, 0xb5, 0x3c, 0xd8, 0x68,
	0x2b, 0x2d, 0x6b, 0xab, 0x07, 0x50, 0x1e, 0xc5, 0x73, 0x27, 0x4a, 0x0d, 0x2b, 0x81, 0x74, 0x36,
	0x9a, 0x5c, 0xa5, 0x92, 0x64, 0x2d, 0x9a, 0x51, 0xc5, 0xc6, 0x6f, 0x21, 0x34, 0x36, 0x59, 0xf2,
	0x22, 0x1b, 0x41, 0x5a, 0x3e, 0x0b, 0xa4, 0xce, 0xd6, 0x0c, 0x22, 0x50, 0x92, 0x55, 0xa9, 0xcb,
	0xb0, 0xe4, 0x5a, 0xcc, 0x1f, 0x19, 0xba, 0x72, 0x6f, 0xd2, 0x54, 0x6a, 0xfd, 0x6d, 0xe4, 0x19,
	0xdf, 0xb9, 0xb9, 0xb4, 0x97, 0xf4, 0xbc, 0x97, 0x8a, 0x03, 0xd6, 0xb8, 0x6b, 0xc0, 0x8a, 0xc1,
	0x46, 0x91, 0xad, 0x42, 0xde, 0x8b, 0xe7, 0x28, 0x87, 0xe1, 0x3e, 0x2d, 0x20, 0x62, 0x04, 0x8c,
	0x3c, 0xee, 0x7f, 0x44, 0x91, 0x2d, 0x35, 0x13, 0x73, 0x40, 0x74, 0x8e, 0xd2, 0x75, 0x90, 0xf9,
	0x49, 0xb0, 0x14, 0x75, 0x6c, 0x57, 0x54, 0xe7, 0xec, 0x10, 0xe4, 0x29, 0x54, 0x45, 0x1e, 0x02,
	0x64, 0x76, 0x55, 0x26, 0xb7, 0x30, 0xff, 0xd6, 0x8c, 0x9a, 0x78, 0x1f, 0x30, 0x49, 0xbc, 0x90,
	0xd9, 0x35, 0x99, 0x84, 0x1c, 0x20, 0x47, 0x50, 0x4b, 0x6f, 0x98, 0xd9, 0xa6, 0x24, 0x33, 0x79,
	0x3d, 0x40, 0x20, 0x1f, 0x20, 0x8f, 0x01, 0xa6, 0x3c, 0x41, 0x6f, 0xf1, 0x36, 0xf4, 0xae, 0xe4,
	0x74, 0xdc, 0xa7, 0x05, 0x44, 0xf1, 0x1e, 0x5f, 0x31, 0x79, 0xf8, 0xbd, 0x35, 0xbf, 0x46, 0xc4,
	0x6d, 0x28, 0x49, 0x8e, 0x46, 0x93, 0xa6, 0x92, 0x38, 0x76, 0xae, 0x35, 0x42, 0xc6, 0xbc, 0x2b,
	0x94, 0xf3, 0xd1, 0xa4, 0xbb, 0x04, 0xb1, 0xa1, 0xba, 0xd6, 0x39, 0x90, 0x3a, 0x6b, 0x51, 0x54,
	0x80, 0x23, 0xae, 0xc8, 0x52, 0x15, 0x20, 0xd6, 0xa2, 0x34, 0x7b, 0xf1, 0x2a, 0xe2, 0xe9, 0x20,
	0x54, 0x42, 0xeb, 0x73, 0x7e, 0xa1, 0x22, 0xaa, 0x71, 0x3c, 0xc7, 0xac, 0x04, 0x52, 0x49, 0x64,
	0xae, 0x17, 0xae, 0x18, 0xc7, 0x24, 0x2b, 0x86, 0x1c, 0x90, 0x79, 0xf5, 0x3e, 0x70, 0xd5, 0xd7,
	0x86, 0x62, 0x33, 0x40, 0xe4, 0x55, 0x08, 0x2e, 0x26, 0x0b, 0x59, 0x04, 0x25, 0x9a, 0xc9, 0xc7,
	0x6f, 0xa0, 0x5e, 0x78, 0xca, 0x48, 0x03, 0x40, 0x3c, 0x96, 0x93, 0xd9, 0xaf, 0xe8, 0x73, 0xeb,
	0x1e, 0x39, 0x80, 0xfa, 0x34, 0x88, 0xae, 0x42, 0x1c, 0xe2, 0x35, 0x86, 0x96, 0x46, 0xea, 0x50,
	0x9d, 0xae, 0x66, 0x3c, 0x41, 0xb4, 0xf4, 0xe3, 0x0b, 0x80, 0xfc, 0xf9, 0x15, 0xd4, 0xc5, 0xf8,
	0xdd, 0x78, 0xf2, 0xf3, 0xd8, 0xba, 0x47, 0xaa, 0x60, 0x9c, 0xf5, 0x5d, 0x4b, 0x13, 0x8b, 0xf3,
	0x0b, 0xd7, 0xd2, 0x49, 0x0d, 0x4a, 0xe7, 0x93, 0xa9, 0x6b, 0x19, 0x04, 0xa0, 0xe2, 0xf4, 0x87,
	0x7d, 0xb7, 0x6f, 0x95, 0x04, 0x3a, 0xfd, 0x65, 0xdc, 0xb3, 0xca, 0x62, 0xf5, 0x93, 0xd8, 0x52,
	0x39, 0xfe, 0x11, 0xea, 0x85, 0x96, 0x92, 0x76, 0xa3, 0x4f, 0x51, 0xfc, 0x7b, 0xa4, 0xec, 0x76,
	0xe7, 0x73, 0x15, 0x08, 0xc5, 0x65, 0xe8, 0xf9, 0x68, 0xe9, 0xd2, 0x22, 0x86, 0xc8, 0xd1, 0x32,
	0xc8, 0x1e, 0xd4, 0x06, 0x91, 0x9f, 0xa0, 0xc7, 0xd0, 0x2a, 0x1d, 0xb3, 0xfc, 0x99, 0x21, 0xfb,
	0x60, 0xba, 0x97, 0x79, 0x88, 0x75, 0xa8, 0xba, 0x97, 0xa7, 0xfd, 0xb3, 0xc1, 0xd8, 0xd2, 0x84,
	0x77, 0xf7, 0xd2, 0x99, 0x58, 0xba, 0xd8, 0xef, 0x5e, 0xf6, 0x26, 0xa3, 0xd1, 0x40, 0xc4, 0xda,
	0x00, 0x70, 0x2f, 0xe9, 0x64, 0x38, 0x3c, 0xed, 0xf6, 0xde, 0x59, 0x25, 0xe1, 0x49, 0xd8, 0x70,
	0x26, 0x56, 0x59, 0xad, 0x87, 0x93, 0xde, 0x3b, 0xab, 0xa2, 0x8c, 0x4d, 0xdd, 0x09, 0xed, 0x5b,
	0xd5, 0xce, 0x9f, 0x3a, 0x18, 0x4e, 0xe7, 0x25, 0x79, 0x02, 0xba, 0x13, 0x93, 0xe2, 0xc0, 0x3e,
	0xda, 0x18, 0xa5, 0xe4, 0x1b, 0xd8, 0xa3, 0xc8, 0xe2, 0xf0, 0x1a, 0xe5, 0x8b, 0x7e, 0x97, 0xea,
	0x73, 0x30, 0xbb, 0x3c, 0x5e, 0x04, 0x7e, 0x77, 0x3e, 0xbf, 0x4b, 0xaf, 0x03, 0xd5, 0xf4, 0x47,
	0x4a, 0x88, 0x7a, 0x50, 0x8b, 0x1f, 0xd6, 0xa3, 0xfb, 0x1b, 0x58, 0xba, 0xe7, 0xff, 0x50, 0x72,
	0x6f, 0xee, 0x8e, 0xf4, 0xb5, 0xc8, 0xa3, 0xfa, 0x74, 0x92, 0xd4, 0xc6, 0xc6, 0x3f, 0xf5, 0xe8,
	0xc1, 0x26, 0x98, 0x6e, 0x7b, 0x23, 0x5f, 0xa5, 0xf4, 0xd3, 0x48, 0x1e, 0x2a, 0x9d, 0xad, 0xbf,
	0xe6, 0xd1, 0xa3, 0x6d, 0x38, 0xdd, 0xdc, 0x06, 0xf3, 0x0c, 0xb9, 0x6a, 0xe9, 0x3b, 0x62, 0xfb,
	0x4e, 0x9b, 0x55, 0xe4, 0x1f, 0xfd, 0xd5, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x37, 0xc7, 0x5c,
	0xe2, 0xb0, 0x0b, 0x00, 0x00,
}
